RaoVat/RaoVat/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaoVat.Models;
using PagedList;
using PagedList.Mvc;

namespace RaoVat.Controllers
{
    public class AdsController : Controller
    {
        // GET: Ads

        DBRaoVatEntities db = new DBRaoVatEntities();
        // GET: Ads
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyTin(int? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            if (Session["TENDANGNHAP"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            else
            {
                var tendangnhap = Session["TENDANGNHAP"];
                var listTin = db.RAOVATs.Where(s => s.USER.TENDANGNHAP == tendangnhap).ToList();
                return View(listTin.ToPagedList(pageNum, pageSize));
            }
        }
        public PartialViewResult AdscatePartial()
        {
            return PartialView();
        }
        public ActionResult SelectState()
        {
            TINHTHANHPHO se_state = new TINHTHANHPHO();
            se_state.ListTinhThanhPho = db.TINHTHANHPHOes.ToList();
            return PartialView(se_state);
        }
        public ActionResult SelectCate()
        {
            CATEGORY se_cate = new CATEGORY();
            se_cate.ListCate = db.CATEGORies.ToList<CATEGORY>();
            return PartialView(se_cate);
        }
        public ActionResult SelectTinhTrang()
        {
            TINHTRANG se_tinhtrang = new TINHTRANG();
            se_tinhtrang.ListTinhTrang = db.TINHTRANGs.ToList<TINHTRANG>();
            return PartialView(se_tinhtrang);
        }
        public ActionResult SelectLoaiTin()
        {
            LOAITIN se_loaitin = new LOAITIN();
            se_loaitin.ListLoaiTin = db.LOAITINs.ToList<LOAITIN>();
            return PartialView(se_loaitin);
        }
        public ActionResult SelectHinhThuc()
        {
            HINHTHUC se_hinhthuc = new HINHTHUC();
            se_hinhthuc.ListHinhThuc = db.HINHTHUCs.ToList<HINHTHUC>();
            return PartialView(se_hinhthuc);
        }
        public ActionResult Create()
        {
            if (Session["TENDANGNHAP"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            else 
            {
                RAOVAT raovat = new RAOVAT();
                return View(raovat); 
            }
        }
        [HttpPost]
        public ActionResult Create(RAOVAT raovat)
        {
            try
            {
                if(raovat.UploadImage !=null){
                    string filename = Path.GetFileNameWithoutExtension(raovat.UploadImage.FileName);
                    string extent = Path.GetExtension(raovat.UploadImage.FileName);
                    filename = filename + extent;
                    raovat.HINHANH1 = "~/Content/img/" + filename;
                    raovat.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/img/"), filename));
                }
                raovat.NGAYGIODANG = DateTime.Now;
                raovat.NGAYHETHAN = DateTime.Now.AddDays(30);
                raovat.MALOAITIN = 1;
                raovat.MATRANGTHAI = 2;
                var userTenDangNhap = Session["TENDANGNHAP"];
                var userCurrent = db.USERs.Where(x => x.TENDANGNHAP == userTenDangNhap.ToString()).FirstOrDefault();
                raovat.MANGUOIDUNG = Convert.ToInt32(userCurrent.MANGUOIDUNG);
                db.RAOVATs.Add(raovat);
                db.SaveChanges();
                return RedirectToAction("Index", "Categories");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            return View(db.RAOVATs.Where(s => s.MATIN == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id, RAOVAT raovat)
        {
            try
            {
                raovat = db.RAOVATs.Where(s => s.MATIN == id).FirstOrDefault();
                db.RAOVATs.Remove(raovat);
                db.SaveChanges();
                return RedirectToAction("QuanLyTin");
            }
            catch
            {
                return Content("This data is using in other table, ERROR DELETE");
            }
        }
        public ActionResult Edit(int id)
        {
            return View(db.RAOVATs.Where(s => s.MATIN == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id, RAOVAT raovat)
        {
            raovat.NGAYGIODANG = DateTime.Now;
            raovat.MALOAITIN = 1;
            raovat.MATRANGTHAI = 2;
            var userTenDangNhap = Session["TENDANGNHAP"];
            var userCurrent = db.USERs.Where(x => x.TENDANGNHAP == userTenDangNhap.ToString()).FirstOrDefault();
            raovat.MANGUOIDUNG = Convert.ToInt32(userCurrent.MANGUOIDUNG);
            db.Entry(raovat).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("QuanLyTin");
        }
        public ActionResult DetailInfo(string id)
        {
            return View(db.USERs.Where(x=>x.TENDANGNHAP == id).FirstOrDefault());
        }
        public ActionResult EditUser(int id)
        {
            return View(db.USERs.Where(s => s.MANGUOIDUNG == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult EditUser(int id, USER user)
        {
            db.USERs.Attach(user);
            user.ErrorLogin = "NULL";
            if (user.GIOITINH == null)
            {
                user.GIOITINH = false;
            }

            if (user.NGAYSINH == null)
            {
                user.NGAYSINH = DateTime.Now;
            }
            if (user.DIACHI == null)
            {
                user.DIACHI = "NULL";
            }
            if (user.ResetPasswordCode == null)
            {
                user.ResetPasswordCode = Guid.NewGuid().ToString();
            }
            db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("QuanLyTin");
        }
    }
}

RaoVat/RaoVat/Views/Ads/AdscatePartial.cshtml
@*<style>
    #div-u {
        background-color: aquamarine;
        text-decoration: none;
    }

    a {
        color: #a94442;
        text-decoration: none;
        font-size: x-large;
    }

        a:hover {
            text-decoration: none;
        }
</style>

<ul style="list-style-type:none" id="div-u">
    <li class="div-cate">
        <a href="/Ads/QuanLyTin">Quản lý rao vặt</a>
    </li>
    <li class="div-cate">
        @{
            if (Session["TENDANGNHAP"] != null)
            {
                var a = Session["TENDANGNHAP"];
                <a href="@Url.Action("DetailInfo","Ads",new { id = a.ToString()})">Thông tin cá nhân</a>
            }
        }

    </li>
    <li class="div-cate">
        <a href="/Ads/Index">Thêm tin rao vặt</a>
    </li>
</ul>*@

<style>
    #div-u {
        list-style-type: none;
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #fff;
        margin-top: 100px;
        border: 1px solid rgba(0, 0, 0, .125);
        border-radius: .25rem;
    }

    .div-cate a {
        display: block;
        color: #000;
        padding: 8px 16px;
        text-decoration: none;
    }

        /* Change the link color on hover */
        .div-cate a:hover {
            background-color: #0d6efd;
            color: white;
        }
</style>
@*<ul id="div-u">
    <li class="div-cate">
        <a href="/Ads/QuanLyTin">Quản lý rao vặt</a>
    </li>
    <li class="div-cate">
        @{
            if (Session["TENDANGNHAP"] != null)
            {
                var a = Session["TENDANGNHAP"];
                <a href="@Url.Action("DetailInfo","Ads",new { id = a.ToString()})">Thông tin cá nhân</a>
            }
        }

    </li>
    <li class="div-cate">
        <a href="/Ads/Create">Thêm tin rao vặt</a>
    </li>

</ul>*@

RaoVat/RaoVat/Views/Ads/Create.cshtml
@model RaoVat.Models.RAOVAT


@{
    ViewBag.Title = "Đăng Tin";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}

<div class="container-fluid bg-body" style="margin-top:100px">
    <div class="row">
        <div class="col-md-2">
            @{ Html.RenderAction("AdscatePartial", "Ads");}
        </div>
        <div class="col-md-10">
            <h2>Đăng Tin</h2>

            @using (Html.BeginForm("Create", "Ads", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thông tin tin rao</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <p>Chọn Danh Mục:</p>
                <div class="col-md-10">
                    @{ Html.RenderAction("SelectCate", "Ads");}
                </div>
            </div>

            <div class="form-group">
                <p>Chọn Tình Trạng Sản Phẩm:</p>
                <div class="col-md-10">
                    @{ Html.RenderAction("SelectTinhTrang", "Ads");}
                </div>
            </div>

            <div class="form-group">
                <p>Chọn Hình Thức:</p>
                <div class="col-md-10">
                    @{ Html.RenderAction("SelectHinhThuc", "Ads");}
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TIEUDE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TIEUDE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIEUDE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HINHANH1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Url.Content(Model.HINHANH1)" width="150" height="150" id="previewImg" />
                    <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NOIDUNG, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NOIDUNG, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NOIDUNG, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GIA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GIA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GIA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p>Chọn Tỉnh, Thành Phố:</p>
                <div class="col-md-10">
                    @{ Html.RenderAction("SelectState", "Ads");}
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Tạo" class="btn btn-primary" />
                </div>
            </div>
        </div>
            }


        </div>
    </div>
</div>
<br />
<br />
<br />

RaoVat/RaoVat/Views/Ads/Delete.cshtml
@model RaoVat.Models.RAOVAT

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}

<div class="container-fluid bg-body" style="margin-top:100px">
    <div class="row">
        <div class="col-md-2">
            @{Html.RenderAction("AdscatePartial", "Ads");}
        </div>
        <div class="col-md-10">
            <h2>Xóa Tin</h2>

            <h3>Bạn chắc chắn muốn xóa tin này?</h3>
            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.TIEUDE)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TIEUDE)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.HINHANH1)
                    </dt>

                    <dd>
                        <img src="@Url.Content(Model.HINHANH1)" width="150" height="150"/>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NOIDUNG)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NOIDUNG)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NGAYGIODANG)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NGAYGIODANG)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.GIA)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GIA)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DIACHI)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DIACHI)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NGAYHETHAN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NGAYHETHAN)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CATEGORY.TENLOAI)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CATEGORY.TENLOAI)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.HINHTHUC.HINHTHUC1)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HINHTHUC.HINHTHUC1)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LOAITIN.LOAITIN1)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LOAITIN.LOAITIN1)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TINHTRANG.TINHTRANG1)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TINHTRANG.TINHTRANG1)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TRANGTHAI.TRANGTHAI1)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TRANGTHAI.TRANGTHAI1)
                    </dd>


                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-primary" /> |
                        @Html.ActionLink("Về Danh sách", "QuanLyTin")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<br />
<br />
<br />

RaoVat/RaoVat/Views/Ads/DetailInfo.cshtml
@model RaoVat.Models.USER

@{
    ViewBag.Title = "DetailInfo";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}


<div class="container-fluid bg-body" style="margin-top:100px">
    <div class="row">
        <div class="col-md-2">
            @{Html.RenderAction("AdscatePartial", "Ads");}
        </div>
        <div class="col-md-10">
            <h2>Thông tin người dùng</h2>

            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.HOTEN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HOTEN)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.GIOITINH)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GIOITINH)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NGAYSINH)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NGAYSINH)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SODIENTHOAI)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SODIENTHOAI)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.EMAIL)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.EMAIL)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DIACHI)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DIACHI)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MATKHAU)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MATKHAU)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Thay đổi", "EditUser", new { id = Model.MANGUOIDUNG } , new { @class = "btn btn-primary" })
            </p>
        </div>
    </div>
</div>

<br />
<br />
<br />

RaoVat/RaoVat/Views/Ads/Edit.cshtml
@model RaoVat.Models.RAOVAT

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}

<div class="container-fluid bg-body" style="margin-top:100px">
    <div class="row">
        <div class="col-md-2">
            @{Html.RenderAction("AdscatePartial", "Ads");}
        </div>
        <div class="col-md-10">
            <h2>Sửa Tin</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Thông tin tin rao</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MATIN)

                    <div class="form-group">
                        <p>Chọn Danh Mục:</p>
                        <div class="col-md-10">
                            @{ Html.RenderAction("SelectCate", "Ads");}
                        </div>
                    </div>

                    <div class="form-group">
                        <p>Chọn Tình Trạng Sản Phẩm:</p>
                        <div class="col-md-10">
                            @{ Html.RenderAction("SelectTinhTrang", "Ads");}
                        </div>
                    </div>

                    <div class="form-group">
                        <p>Chọn Hình Thức:</p>
                        <div class="col-md-10">
                            @{ Html.RenderAction("SelectHinhThuc", "Ads");}
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TIEUDE, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TIEUDE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TIEUDE, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HINHANH1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img src="@Url.Content(Model.HINHANH1)" width="150" height="150" id="previewImg" />
                            <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NOIDUNG, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NOIDUNG, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NOIDUNG, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.GIA, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GIA, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GIA, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <p>Chọn Tỉnh, Thành Phố:</p>
                        <div class="col-md-10">
                            @{ Html.RenderAction("SelectState", "Ads");}
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-primary" /> |
                            @Html.ActionLink("Về Danh sách", "QuanLyTin")
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<br />
<br />
<br />

RaoVat/RaoVat/Views/Ads/EditUser.cshtml
@model RaoVat.Models.USER

@{
    ViewBag.Title = "EditUser";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}


<div class="container-fluid bg-body" style="margin-top:100px">
    <div class="row">
        <div class="col-md-2">
            @{Html.RenderAction("AdscatePartial", "Ads");}
        </div>
        <div class="col-md-10">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <br />
                <h3>Thay đổi thông tin người dùng</h3>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MANGUOIDUNG)
                @Html.HiddenFor(model => model.TENDANGNHAP)

                @*<div class="form-group">
                    <h4>Tên người dùng</h4>
                    <div class="col-md-10">
                        <h4>@Html.DisplayFor(model => model.TENDANGNHAP)</h4>
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.HOTEN, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GIOITINH, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.RadioButton("GIOITINH", true, new { htmlAttributes = new { @class = "form-control" } })
                        <span>Nam</span>
                        @Html.RadioButton("GIOITINH", false, new { htmlAttributes = new { @class = "form-control" } })
                        <span>Nữ</span>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SODIENTHOAI, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SODIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SODIENTHOAI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MATKHAU, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConfirmPass, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfirmPass, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmPass, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

<br />
<br />
<br />

RaoVat/RaoVat/Views/Ads/SelectCate.cshtml
@model RaoVat.Models.CATEGORY
@Html.DropDownListFor(model => model.MALOAI,
new SelectList(Model.ListCate.OrderBy(model => model.TENLOAI), "MALOAI", "TENLOAI"), "--Chọn Danh Mục--")

RaoVat/RaoVat/Views/Ads/SelectHinhThuc.cshtml
@model RaoVat.Models.HINHTHUC
@Html.DropDownListFor(model => model.MAHINHTHUC,
    new SelectList(Model.ListHinhThuc.OrderBy(model => model.HINHTHUC1), "MAHINHTHUC", "HINHTHUC1"), "--Chọn Hình Thức--")

RaoVat/RaoVat/Views/Ads/SelectLoaiTin.cshtml
@model RaoVat.Models.LOAITIN
@Html.DropDownListFor(model => model.MALOAITIN,
    new SelectList(Model.ListLoaiTin.OrderBy(model => model.LOAITIN1), "MALOAITIN", "LOAITIN1"), "--Chọn Loại Tin--")

RaoVat/RaoVat/Views/Ads/SelectState.cshtml
@model RaoVat.Models.TINHTHANHPHO
@Html.DropDownListFor(model => model.MATHANHPHO,
new SelectList(Model.ListTinhThanhPho.OrderBy(model => model.TENTHANHPHO), "MATHANHPHO", "TENTHANHPHO"), "--Chọn Tỉnh, Thành Phố--")

RaoVat/RaoVat/Views/Ads/SelectTinhTrang.cshtml
@model RaoVat.Models.TINHTRANG
@Html.DropDownListFor(model => model.MATINHTRANG,
    new SelectList(Model.ListTinhTrang.OrderBy(model=>model.TINHTRANG1), "MATINHTRANG", "TINHTRANG1"),"--Chọn Tình Trạng--")

RaoVat/RaoVat/Views/Ads/gioihan.cshtml
@{
    ViewBag.Title = "gioihan";
    Layout = "~/Views/Shared/_LayoutTrangChu.cshtml";
}

<h2 style="text-align:center;margin-top:100px">bạn đã đạt đến giới hạn đăng tin</h2>